export const ORDER_DELIVERY_ADDRESS_MAX_LENGTH = 255;
export const ORDER_DELIVERY_INSTRUCTIONS_MAX_LENGTH = 500;
export const ORDER_TOTAL_PRICE_PRECISION = 10;
export const ORDER_TOTAL_PRICE_SCALE = 2;
